/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.16.5 on Tue Jan 20 20:27:30 2015
 *
 * Copyright (c) 2014 Riverbank Computing Limited <info@riverbankcomputing.com>
 * 
 * This file is part of PyQt.
 * 
 * This file may be used under the terms of the GNU General Public
 * License versions 2.0 or 3.0 as published by the Free Software
 * Foundation and appearing in the files LICENSE.GPL2 and LICENSE.GPL3
 * included in the packaging of this file.  Alternatively you may (at
 * your option) use any later version of the GNU General Public
 * License if such license has been publicly approved by Riverbank
 * Computing Limited (or its successors, if any) and the KDE Free Qt
 * Foundation. In addition, as a special exception, Riverbank gives you
 * certain additional rights. These rights are described in the Riverbank
 * GPL Exception version 1.1, which can be found in the file
 * GPL_EXCEPTION.txt in this package.
 * 
 * If you are unsure which license is appropriate for your use, please
 * contact the sales department at sales@riverbankcomputing.com.
 * 
 * This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
 * WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */

#include "sipAPIQtHelp.h"

#line 56 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/sip/QtHelp/qhelpindexwidget.sip"
#include <qhelpindexwidget.h>
#line 34 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"

#line 36 "sip/QtCore/qstring.sip"
#include <qstring.h>
#line 38 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 33 "sip/QtCore/qmap.sip"
#include <qmap.h>
#line 41 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 77 "sip/QtCore/qstring.sip"
#include <qstring.h>
#line 44 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 107 "sip/QtCore/qurl.sip"
#include <qurl.h>
#line 47 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 31 "sip/QtCore/qabstractitemmodel.sip"
#include <qabstractitemmodel.h>
#line 50 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 174 "sip/QtGui/qitemselectionmodel.sip"
#include <qitemselectionmodel.h>
#line 53 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 33 "sip/QtCore/qlist.sip"
#include <qlist.h>
#line 56 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 35 "sip/QtGui/qregion.sip"
#include <qregion.h>
#line 59 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 35 "sip/QtCore/qrect.sip"
#include <qrect.h>
#line 62 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 94 "sip/QtGui/qitemselectionmodel.sip"
#include <qitemselectionmodel.h>
#line 65 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 35 "sip/QtCore/qpoint.sip"
#include <qpoint.h>
#line 68 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 35 "sip/QtGui/qabstractitemview.sip"
#include <qabstractitemview.h>
#line 71 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 35 "sip/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 74 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 533 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 77 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 1135 "sip/QtGui/qstyleoption.sip"
#include <qstyleoption.h>
#line 80 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 35 "sip/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 83 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 748 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 86 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 801 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 89 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 774 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 92 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 570 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 95 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 338 "sip/QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 98 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 261 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 101 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 31 "sip/QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 104 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 31 "sip/QtGui/qlistview.sip"
#include <qlistview.h>
#line 107 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 35 "sip/QtCore/qsize.sip"
#include <qsize.h>
#line 110 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 35 "sip/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 113 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 656 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 116 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 274 "sip/QtCore/qvariant.sip"
#include <qvariant.h>
#line 119 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 31 "sip/QtGui/qabstractitemdelegate.sip"
#include <qabstractitemdelegate.h>
#line 122 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 483 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 125 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 514 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 128 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 790 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 131 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 34 "sip/QtCore/qobject.sip"
#include <qobject.h>
#line 134 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 35 "sip/QtGui/qwidget.sip"
#include <qwidget.h>
#line 137 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 35 "sip/QtGui/qabstractitemview.sip"
#include <qabstractitemview.h>
#line 140 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 94 "sip/QtGui/qitemselectionmodel.sip"
#include <qitemselectionmodel.h>
#line 143 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 127 "sip/QtCore/qabstractitemmodel.sip"
#include <qabstractitemmodel.h>
#line 146 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 120 "sip/QtCore/qlist.sip"
#include <qlist.h>
#line 149 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 35 "sip/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 152 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 31 "sip/QtGui/qscrollbar.sip"
#include <qscrollbar.h>
#line 155 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 627 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 158 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 356 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 161 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 39 "sip/QtCore/qmargins.sip"
#include <qmargins.h>
#line 164 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 35 "sip/QtGui/qpainter.sip"
#include <qpainter.h>
#line 167 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 31 "sip/QtGui/qframe.sip"
#include <qframe.h>
#line 170 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 35 "sip/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 173 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 35 "sip/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 176 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 39 "sip/QtGui/qgraphicseffect.sip"
#include <qgraphicseffect.h>
#line 179 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 33 "sip/QtGui/qgraphicsproxywidget.sip"
#include <qgraphicsproxywidget.h>
#line 182 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 35 "sip/QtCore/qlocale.sip"
#include <qlocale.h>
#line 185 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 31 "sip/QtGui/qpaintdevice.sip"
#include <qpaintdevice.h>
#line 188 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 35 "sip/QtGui/qwidget.sip"
#include <qwidget.h>
#line 191 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 37 "sip/QtCore/qbytearray.sip"
#include <qbytearray.h>
#line 194 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 31 "sip/QtGui/qfontinfo.sip"
#include <qfontinfo.h>
#line 197 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 31 "sip/QtGui/qfontmetrics.sip"
#include <qfontmetrics.h>
#line 200 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 35 "sip/QtGui/qfont.sip"
#include <qfont.h>
#line 203 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 35 "sip/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 206 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 35 "sip/QtGui/qpalette.sip"
#include <qpalette.h>
#line 209 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 616 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 212 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 605 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 215 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 863 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 218 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 412 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 221 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 583 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 224 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 557 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 227 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 33 "sip/QtGui/qinputcontext.sip"
#include <qinputcontext.h>
#line 230 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 61 "sip/QtGui/qpaintengine.sip"
#include <qpaintengine.h>
#line 233 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 120 "sip/QtCore/qlist.sip"
#include <qlist.h>
#line 236 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 31 "sip/QtGui/qaction.sip"
#include <qaction.h>
#line 239 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 31 "sip/QtGui/qlayout.sip"
#include <qlayout.h>
#line 242 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 35 "sip/QtGui/qsizepolicy.sip"
#include <qsizepolicy.h>
#line 245 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 35 "sip/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 248 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 35 "sip/QtGui/qkeysequence.sip"
#include <qkeysequence.h>
#line 251 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 35 "sip/QtGui/qcursor.sip"
#include <qcursor.h>
#line 254 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 35 "sip/QtGui/qicon.sip"
#include <qicon.h>
#line 257 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 35 "sip/QtGui/qbitmap.sip"
#include <qbitmap.h>
#line 260 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 35 "sip/QtGui/qstyle.sip"
#include <qstyle.h>
#line 263 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 355 "sip/QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 266 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 33 "sip/QtCore/qlist.sip"
#include <qlist.h>
#line 269 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 120 "sip/QtCore/qlist.sip"
#include <qlist.h>
#line 272 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 31 "sip/QtCore/qthread.sip"
#include <qthread.h>
#line 275 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 35 "sip/QtCore/qregexp.sip"
#include <qregexp.h>
#line 278 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 31 "sip/QtCore/qobjectdefs.sip"
#include <qobjectdefs.h>
#line 281 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"


PyDoc_STRVAR(doc_QHelpIndexWidget_filterIndices, "QHelpIndexWidget.filterIndices(QString, QString wildcard=QString())");

extern "C" {static PyObject *meth_QHelpIndexWidget_filterIndices(PyObject *, PyObject *, PyObject *);}
static PyObject *meth_QHelpIndexWidget_filterIndices(PyObject *sipSelf, PyObject *sipArgs, PyObject *sipKwds)
{
    PyObject *sipParseErr = NULL;

    {
        const QString* a0;
        int a0State = 0;
        const QString& a1def = QString();
        const QString* a1 = &a1def;
        int a1State = 0;
        QHelpIndexWidget *sipCpp;

        static const char *sipKwdList[] = {
            NULL,
            sipName_wildcard,
        };

        if (sipParseKwdArgs(&sipParseErr, sipArgs, sipKwds, sipKwdList, NULL, "BJ1|J1", &sipSelf, sipType_QHelpIndexWidget, &sipCpp, sipType_QString,&a0, &a0State, sipType_QString,&a1, &a1State))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp->filterIndices(*a0,*a1);
            Py_END_ALLOW_THREADS
            sipReleaseType(const_cast<QString *>(a0),sipType_QString,a0State);
            sipReleaseType(const_cast<QString *>(a1),sipType_QString,a1State);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QHelpIndexWidget, sipName_filterIndices, doc_QHelpIndexWidget_filterIndices);

    return NULL;
}


PyDoc_STRVAR(doc_QHelpIndexWidget_activateCurrentItem, "QHelpIndexWidget.activateCurrentItem()");

extern "C" {static PyObject *meth_QHelpIndexWidget_activateCurrentItem(PyObject *, PyObject *);}
static PyObject *meth_QHelpIndexWidget_activateCurrentItem(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QHelpIndexWidget *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QHelpIndexWidget, &sipCpp))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp->activateCurrentItem();
            Py_END_ALLOW_THREADS

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QHelpIndexWidget, sipName_activateCurrentItem, doc_QHelpIndexWidget_activateCurrentItem);

    return NULL;
}


/* Cast a pointer to a type somewhere in its superclass hierarchy. */
extern "C" {static void *cast_QHelpIndexWidget(void *, const sipTypeDef *);}
static void *cast_QHelpIndexWidget(void *ptr, const sipTypeDef *targetType)
{
    void *res;

    if (targetType == sipType_QHelpIndexWidget)
        return ptr;

    if ((res = ((const sipClassTypeDef *)sipType_QListView)->ctd_cast((QListView *)(QHelpIndexWidget *)ptr,targetType)) != NULL)
        return res;

    return NULL;
}


/* Call the instance's destructor. */
extern "C" {static void release_QHelpIndexWidget(void *, int);}
static void release_QHelpIndexWidget(void *sipCppV,int)
{
    QHelpIndexWidget *sipCpp = reinterpret_cast<QHelpIndexWidget *>(sipCppV);

    Py_BEGIN_ALLOW_THREADS

    if (QThread::currentThread() == sipCpp->thread())
        delete sipCpp;
    else
        sipCpp->deleteLater();

    Py_END_ALLOW_THREADS
}


extern "C" {static void dealloc_QHelpIndexWidget(sipSimpleWrapper *);}
static void dealloc_QHelpIndexWidget(sipSimpleWrapper *sipSelf)
{
    if (sipIsPyOwned(sipSelf))
    {
        release_QHelpIndexWidget(sipGetAddress(sipSelf),0);
    }
}


/* Define this type's super-types. */
static sipEncodedTypeDef supers_QHelpIndexWidget[] = {{314, 1, 1}};


static PyMethodDef methods_QHelpIndexWidget[] = {
    {SIP_MLNAME_CAST(sipName_activateCurrentItem), meth_QHelpIndexWidget_activateCurrentItem, METH_VARARGS, SIP_MLDOC_CAST(doc_QHelpIndexWidget_activateCurrentItem)},
    {SIP_MLNAME_CAST(sipName_filterIndices), (PyCFunction)meth_QHelpIndexWidget_filterIndices, METH_VARARGS|METH_KEYWORDS, SIP_MLDOC_CAST(doc_QHelpIndexWidget_filterIndices)}
};


/* Define this type's signals. */
static const pyqt4QtSignal signals_QHelpIndexWidget[] = {
    {"linksActivated(QMap<QString,QUrl>,QString)", "\1QHelpIndexWidget.linksActivated[dict-of-QString-QUrl, QString]", 0, 0},
    {"linkActivated(QUrl,QString)", "\1QHelpIndexWidget.linkActivated[QUrl, QString]", 0, 0},
    {0, 0, 0, 0}
};


pyqt4ClassTypeDef sipTypeDef_QtHelp_QHelpIndexWidget = {
{
    {
        -1,
        0,
        0,
        SIP_TYPE_SCC|SIP_TYPE_CLASS,
        sipNameNr_QHelpIndexWidget,
        {0}
    },
    {
        sipNameNr_QHelpIndexWidget,
        {0, 0, 1},
        2, methods_QHelpIndexWidget,
        0, 0,
        0, 0,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    },
    0,
    -1,
    -1,
    supers_QHelpIndexWidget,
    0,
    0,
    0,
    0,
#if PY_MAJOR_VERSION >= 3
    0,
    0,
#else
    0,
    0,
    0,
    0,
#endif
    dealloc_QHelpIndexWidget,
    0,
    0,
    0,
    release_QHelpIndexWidget,
    cast_QHelpIndexWidget,
    0,
    0,
    0,
    0,
    0,
    0
},
    &QHelpIndexWidget::staticMetaObject,
    0,
    signals_QHelpIndexWidget,
};
