/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.16.5 on Tue Jan 20 20:27:30 2015
 *
 * Copyright (c) 2014 Riverbank Computing Limited <info@riverbankcomputing.com>
 * 
 * This file is part of PyQt.
 * 
 * This file may be used under the terms of the GNU General Public
 * License versions 2.0 or 3.0 as published by the Free Software
 * Foundation and appearing in the files LICENSE.GPL2 and LICENSE.GPL3
 * included in the packaging of this file.  Alternatively you may (at
 * your option) use any later version of the GNU General Public
 * License if such license has been publicly approved by Riverbank
 * Computing Limited (or its successors, if any) and the KDE Free Qt
 * Foundation. In addition, as a special exception, Riverbank gives you
 * certain additional rights. These rights are described in the Riverbank
 * GPL Exception version 1.1, which can be found in the file
 * GPL_EXCEPTION.txt in this package.
 * 
 * If you are unsure which license is appropriate for your use, please
 * contact the sales department at sales@riverbankcomputing.com.
 * 
 * This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
 * WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */

#include "sipAPIQtHelp.h"

#line 33 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/sip/QtHelp/qhelpsearchresultwidget.sip"
#include <qhelpsearchresultwidget.h>
#line 34 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpSearchResultWidget.cpp"

#line 107 "sip/QtCore/qurl.sip"
#include <qurl.h>
#line 38 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpSearchResultWidget.cpp"
#line 35 "sip/QtCore/qpoint.sip"
#include <qpoint.h>
#line 41 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpSearchResultWidget.cpp"
#line 35 "sip/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 44 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpSearchResultWidget.cpp"
#line 35 "sip/QtGui/qwidget.sip"
#include <qwidget.h>
#line 47 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpSearchResultWidget.cpp"
#line 39 "sip/QtCore/qmargins.sip"
#include <qmargins.h>
#line 50 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpSearchResultWidget.cpp"
#line 35 "sip/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 53 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpSearchResultWidget.cpp"
#line 35 "sip/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 56 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpSearchResultWidget.cpp"
#line 39 "sip/QtGui/qgraphicseffect.sip"
#include <qgraphicseffect.h>
#line 59 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpSearchResultWidget.cpp"
#line 33 "sip/QtGui/qgraphicsproxywidget.sip"
#include <qgraphicsproxywidget.h>
#line 62 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpSearchResultWidget.cpp"
#line 36 "sip/QtCore/qstring.sip"
#include <qstring.h>
#line 65 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpSearchResultWidget.cpp"
#line 35 "sip/QtCore/qlocale.sip"
#include <qlocale.h>
#line 68 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpSearchResultWidget.cpp"
#line 31 "sip/QtGui/qpaintdevice.sip"
#include <qpaintdevice.h>
#line 71 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpSearchResultWidget.cpp"
#line 35 "sip/QtGui/qregion.sip"
#include <qregion.h>
#line 74 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpSearchResultWidget.cpp"
#line 35 "sip/QtGui/qwidget.sip"
#include <qwidget.h>
#line 77 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpSearchResultWidget.cpp"
#line 35 "sip/QtGui/qpainter.sip"
#include <qpainter.h>
#line 80 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpSearchResultWidget.cpp"
#line 37 "sip/QtCore/qbytearray.sip"
#include <qbytearray.h>
#line 83 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpSearchResultWidget.cpp"
#line 35 "sip/QtCore/qsize.sip"
#include <qsize.h>
#line 86 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpSearchResultWidget.cpp"
#line 35 "sip/QtCore/qrect.sip"
#include <qrect.h>
#line 89 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpSearchResultWidget.cpp"
#line 31 "sip/QtGui/qfontinfo.sip"
#include <qfontinfo.h>
#line 92 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpSearchResultWidget.cpp"
#line 31 "sip/QtGui/qfontmetrics.sip"
#include <qfontmetrics.h>
#line 95 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpSearchResultWidget.cpp"
#line 35 "sip/QtGui/qfont.sip"
#include <qfont.h>
#line 98 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpSearchResultWidget.cpp"
#line 35 "sip/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 101 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpSearchResultWidget.cpp"
#line 35 "sip/QtGui/qpalette.sip"
#include <qpalette.h>
#line 104 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpSearchResultWidget.cpp"
#line 274 "sip/QtCore/qvariant.sip"
#include <qvariant.h>
#line 107 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpSearchResultWidget.cpp"
#line 656 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 110 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpSearchResultWidget.cpp"
#line 31 "sip/QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 113 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpSearchResultWidget.cpp"
#line 616 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 116 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpSearchResultWidget.cpp"
#line 605 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 119 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpSearchResultWidget.cpp"
#line 748 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 122 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpSearchResultWidget.cpp"
#line 801 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 125 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpSearchResultWidget.cpp"
#line 774 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 128 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpSearchResultWidget.cpp"
#line 790 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 131 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpSearchResultWidget.cpp"
#line 863 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 134 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpSearchResultWidget.cpp"
#line 412 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 137 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpSearchResultWidget.cpp"
#line 627 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 140 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpSearchResultWidget.cpp"
#line 583 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 143 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpSearchResultWidget.cpp"
#line 570 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 146 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpSearchResultWidget.cpp"
#line 557 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 149 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpSearchResultWidget.cpp"
#line 533 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 152 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpSearchResultWidget.cpp"
#line 514 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 155 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpSearchResultWidget.cpp"
#line 483 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 158 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpSearchResultWidget.cpp"
#line 356 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 161 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpSearchResultWidget.cpp"
#line 261 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 164 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpSearchResultWidget.cpp"
#line 33 "sip/QtGui/qinputcontext.sip"
#include <qinputcontext.h>
#line 167 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpSearchResultWidget.cpp"
#line 61 "sip/QtGui/qpaintengine.sip"
#include <qpaintengine.h>
#line 170 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpSearchResultWidget.cpp"
#line 120 "sip/QtCore/qlist.sip"
#include <qlist.h>
#line 173 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpSearchResultWidget.cpp"
#line 31 "sip/QtGui/qaction.sip"
#include <qaction.h>
#line 176 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpSearchResultWidget.cpp"
#line 31 "sip/QtGui/qlayout.sip"
#include <qlayout.h>
#line 179 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpSearchResultWidget.cpp"
#line 35 "sip/QtGui/qsizepolicy.sip"
#include <qsizepolicy.h>
#line 182 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpSearchResultWidget.cpp"
#line 35 "sip/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 185 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpSearchResultWidget.cpp"
#line 35 "sip/QtGui/qkeysequence.sip"
#include <qkeysequence.h>
#line 188 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpSearchResultWidget.cpp"
#line 35 "sip/QtGui/qcursor.sip"
#include <qcursor.h>
#line 191 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpSearchResultWidget.cpp"
#line 35 "sip/QtGui/qicon.sip"
#include <qicon.h>
#line 194 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpSearchResultWidget.cpp"
#line 35 "sip/QtGui/qbitmap.sip"
#include <qbitmap.h>
#line 197 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpSearchResultWidget.cpp"
#line 35 "sip/QtGui/qstyle.sip"
#include <qstyle.h>
#line 200 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpSearchResultWidget.cpp"
#line 355 "sip/QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 203 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpSearchResultWidget.cpp"
#line 338 "sip/QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 206 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpSearchResultWidget.cpp"
#line 34 "sip/QtCore/qobject.sip"
#include <qobject.h>
#line 209 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpSearchResultWidget.cpp"
#line 33 "sip/QtCore/qlist.sip"
#include <qlist.h>
#line 212 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpSearchResultWidget.cpp"
#line 120 "sip/QtCore/qlist.sip"
#include <qlist.h>
#line 215 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpSearchResultWidget.cpp"
#line 31 "sip/QtCore/qthread.sip"
#include <qthread.h>
#line 218 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpSearchResultWidget.cpp"
#line 35 "sip/QtCore/qregexp.sip"
#include <qregexp.h>
#line 221 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpSearchResultWidget.cpp"
#line 31 "sip/QtCore/qobjectdefs.sip"
#include <qobjectdefs.h>
#line 224 "/Users/ktaylora/PLJV/tillage_likelihood_model/gui/PyQt4/QtHelp/sipQtHelpQHelpSearchResultWidget.cpp"


PyDoc_STRVAR(doc_QHelpSearchResultWidget_linkAt, "QHelpSearchResultWidget.linkAt(QPoint) -> QUrl");

extern "C" {static PyObject *meth_QHelpSearchResultWidget_linkAt(PyObject *, PyObject *);}
static PyObject *meth_QHelpSearchResultWidget_linkAt(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QPoint* a0;
        QHelpSearchResultWidget *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ9", &sipSelf, sipType_QHelpSearchResultWidget, &sipCpp, sipType_QPoint, &a0))
        {
            QUrl*sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = new QUrl(sipCpp->linkAt(*a0));
            Py_END_ALLOW_THREADS

            return sipConvertFromNewType(sipRes,sipType_QUrl,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QHelpSearchResultWidget, sipName_linkAt, doc_QHelpSearchResultWidget_linkAt);

    return NULL;
}


/* Cast a pointer to a type somewhere in its superclass hierarchy. */
extern "C" {static void *cast_QHelpSearchResultWidget(void *, const sipTypeDef *);}
static void *cast_QHelpSearchResultWidget(void *ptr, const sipTypeDef *targetType)
{
    void *res;

    if (targetType == sipType_QHelpSearchResultWidget)
        return ptr;

    if ((res = ((const sipClassTypeDef *)sipType_QWidget)->ctd_cast((QWidget *)(QHelpSearchResultWidget *)ptr,targetType)) != NULL)
        return res;

    return NULL;
}


/* Call the instance's destructor. */
extern "C" {static void release_QHelpSearchResultWidget(void *, int);}
static void release_QHelpSearchResultWidget(void *sipCppV,int)
{
    QHelpSearchResultWidget *sipCpp = reinterpret_cast<QHelpSearchResultWidget *>(sipCppV);

    Py_BEGIN_ALLOW_THREADS

    if (QThread::currentThread() == sipCpp->thread())
        delete sipCpp;
    else
        sipCpp->deleteLater();

    Py_END_ALLOW_THREADS
}


extern "C" {static void dealloc_QHelpSearchResultWidget(sipSimpleWrapper *);}
static void dealloc_QHelpSearchResultWidget(sipSimpleWrapper *sipSelf)
{
    if (sipIsPyOwned(sipSelf))
    {
        release_QHelpSearchResultWidget(sipGetAddress(sipSelf),0);
    }
}


/* Define this type's super-types. */
static sipEncodedTypeDef supers_QHelpSearchResultWidget[] = {{757, 1, 1}};


static PyMethodDef methods_QHelpSearchResultWidget[] = {
    {SIP_MLNAME_CAST(sipName_linkAt), meth_QHelpSearchResultWidget_linkAt, METH_VARARGS, SIP_MLDOC_CAST(doc_QHelpSearchResultWidget_linkAt)}
};


/* Define this type's signals. */
static const pyqt4QtSignal signals_QHelpSearchResultWidget[] = {
    {"requestShowLink(QUrl)", "\1QHelpSearchResultWidget.requestShowLink[QUrl]", 0, 0},
    {0, 0, 0, 0}
};


pyqt4ClassTypeDef sipTypeDef_QtHelp_QHelpSearchResultWidget = {
{
    {
        -1,
        0,
        0,
        SIP_TYPE_SCC|SIP_TYPE_CLASS,
        sipNameNr_QHelpSearchResultWidget,
        {0}
    },
    {
        sipNameNr_QHelpSearchResultWidget,
        {0, 0, 1},
        1, methods_QHelpSearchResultWidget,
        0, 0,
        0, 0,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    },
    0,
    -1,
    -1,
    supers_QHelpSearchResultWidget,
    0,
    0,
    0,
    0,
#if PY_MAJOR_VERSION >= 3
    0,
    0,
#else
    0,
    0,
    0,
    0,
#endif
    dealloc_QHelpSearchResultWidget,
    0,
    0,
    0,
    release_QHelpSearchResultWidget,
    cast_QHelpSearchResultWidget,
    0,
    0,
    0,
    0,
    0,
    0
},
    &QHelpSearchResultWidget::staticMetaObject,
    0,
    signals_QHelpSearchResultWidget,
};
